### ISSUE TITLE
Mouse cursor size

### ISSUE THREAD

**Issue by medicamin** [realmazharhussain/gdm-settings#150] opened 2023-03-05 11:23 UTC
### Description

an option to change the mouse cursor size

### Explanation

In hidpi resolutions, mouse cursor gets too tiny in gdm. I could change the cursor size to my preferred size by doing this in root terminal:

`sudo -u gdm dbus-launch gsettings set org.gnome.desktop.interface cursor-size 24
`
could you please add an option below the cursor theme, so as we could change size easily?

**Comment by realmazharhussain** [comment] 2023-03-05 19:21
Duplicate of https://github.com/realmazharhussain/gdm-settings/issues/138

https://github.com/realmazharhussain/gdm-settings/raw/screenshots/dark/screenshot-5.png

**Closed by realmazharhussain** 2023-03-05 19:21 UTC
Labels: enhancement
