### ISSUE TITLE
Background Image and Shell Theme Not Applied, Pop_OS 22.04

### ISSUE THREAD

**Issue by KineticAeon** [realmazharhussain/gdm-settings#157] opened 2023-04-09 22:46 UTC
### What happened?

In appearance, the background and shell settings do not work and nothing changes.

### Expected behavior

The background should be set to an image and the login screen colors should change to those of the new shell theme.

### To Reproduce

1. Open Login Manager Settings.
2. Change background and shell.
3. Press apply.
4. Restart.

### Detailed Explanation (Optional)

Note: The welcome message works.

### Application Version

2.1

### Format/Source

Flatpak

### Environment

- **OS**: Pop OS 22.04
- **GNOME**: 42.5

**Comment by realmazharhussain** [comment] 2023-04-10 06:22
Duplicate of https://github.com/realmazharhussain/gdm-settings/issues/129.

**Closed by realmazharhussain** 2023-04-10 06:22 UTC
Labels: bug
