### ISSUE TITLE
How to reset GDM ?

### ISSUE THREAD

**Issue by FarisZR** [realmazharhussain/gdm-settings#49] opened 2022-05-10 21:21 UTC
Hello, 
I changed some settings and now GDM doesn't work.

How can you reset the settings to the defaults of the distro?
What files to delete/change ?

**Comment by realmazharhussain** [comment] 2022-05-11 02:06
If not on Ubuntu, run the following commands as root

```bash
mv -f /usr/share/gnome-shell/gnome-shell-theme.gresource{.default,}
rm -f /etc/dconf/db/gdm.d/95-gdm-settings
dconf update
```

If on Ubuntu 21.10 or higher, run the following commands as root

```bash
update-alternatives --remove gdm-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.gdm_settings
rm -f /usr/share/gnome-shell/gnome-shell-theme.gresource.gdm_settings
rm -f /etc/dconf/db/gdm.d/95-gdm-settings
dconf update
```

If on Ubuntu 21.04 or lower, run the following commands as root

```bash
update-alternatives --remove gdm3-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.gdm_settings
rm -f /usr/share/gnome-shell/gnome-shell-theme.gresource.gdm_settings
rm -f /etc/dconf/db/gdm.d/95-gdm-settings
dconf update
```

**Comment by stefanmaric** [comment] 2022-05-14 13:33
@realmazharhussain what other files might gdm-settings update on non-ubuntu systems?

I did some updates like background, welcome message, and showing weekend+seconds in top bar and I completely broke GDM. 😅

Resetting the shell theme and removing the dconf files as suggested didn't help in my case. I'm on Fedora 36 and I'm using the propietary Nvidia drivers from RPM Fusion. Might have something to do?

I just installed so worst case scenario I reinstall, but seeing if I can fix it in some other way to save time.

**Comment by stefanmaric** [comment] 2022-05-14 16:38
Using the system journal I was able to pin-point the error:

```shell
may 14 16:16:35 fedora audit[14729]: AVC avc:  denied  { map } for  pid=14729 comm="gnome-shell" path="/usr/share/gnome-shell/gnome-shell-theme.gresource" dev="dm-0" ino=600681 scontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0
may 14 16:16:35 fedora gnome-shell[14729]: JS ERROR: GLib.FileError: Failed to map /usr/share/gnome-shell/gnome-shell-theme.gresource' /usr/share/gnome-shell/gnome-shell-theme.gresource': mmap() failed: Permission denied
                                           reloadThemeResource@resource:///org/gnome/shell/ui/main.js:440:35
                                           _initializeUI@resource:///org/gnome/shell/ui/main.js:192:5
                                           start@resource:///org/gnome/shell/ui/main.js:165:5
                                           @resource:///org/gnome/shell/ui/init.js:6:17
may 14 16:16:35 fedora gnome-shell[14729]: Execution of main.js threw exception: Module resource:///org/gnome/shell/ui/init.js threw an exception
may 14 16:16:35 fedora gnome-session[14697]: gnome-session-binary[14697]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
```

I didn't see anything strange about the file permissions tho.

Thinking it might have been something about the content instead of the file descriptors, I ran `sudo rpm -qf /usr/share/gnome-shell/gnome-shell-theme.gresource` to determine from which package it originally comes from: `gnome-shell`

I was able to fix it by reinstalling gnome-shell with `sudo dnf reinstall gnome-shell` and then restarting gdm with `sudo systemctl restart gdm.service`.

I was able to login correctly. I opened `gdm-settings` and then "Reset settings" using the dots menu and applied the changes.

I logged out and gdm was broken again. :sob:

So even with "default" settings, applying anything at all on my system is breaking gdm.

Fortunately, I was yet again able to fix it by reinstalling `gnome-shell`. So the issue must lay in one of `gnome-shell`'s files:

```shell
$ rpm -ql gnome-shell
/etc/xdg/autostart/gnome-shell-overrides-migration.desktop
/usr/bin/gnome-extensions
/usr/bin/gnome-shell
/usr/bin/gnome-shell-extension-prefs
/usr/bin/gnome-shell-extension-tool
/usr/bin/gnome-shell-perf-tool
/usr/lib/.build-id
/usr/lib/.build-id/17
/usr/lib/.build-id/17/07294825bc740cf1609b223a791c74236fc467
/usr/lib/.build-id/17/4540c1664eccfd36278ebb539c501f4f035119
/usr/lib/.build-id/51
/usr/lib/.build-id/51/664f85f44a8fccb9a9e2e807aecbedbbed40ce
/usr/lib/.build-id/65
/usr/lib/.build-id/65/a2dca7354edf4d0a0afec8746d85220d9b1dcb
/usr/lib/.build-id/72
/usr/lib/.build-id/72/f20c56943d1fb54c5fe5d6563426705ab34e7b
/usr/lib/.build-id/89
/usr/lib/.build-id/89/82f542f9e3ab0b3d08de92cfb897d90c0569be
/usr/lib/.build-id/9f
/usr/lib/.build-id/9f/e7fdbc2f7352698398796a2e04510a182b8f0e
/usr/lib/.build-id/a8
/usr/lib/.build-id/a8/ccaf8b335385b31bc8aae21770351cc4740ebd
/usr/lib/.build-id/e8
/usr/lib/.build-id/e8/61acd70cade5b3c22683895623a6cce2b9e16b
/usr/lib/.build-id/ed
/usr/lib/.build-id/ed/908dd7b2bf27593cb1eb7a077a16b0a7679416
/usr/lib/.build-id/fa
/usr/lib/.build-id/fa/84e259ee27d2ad7fe7f274636b6c502077522f
/usr/lib/systemd/user/org.gnome.Shell-disable-extensions.service
/usr/lib/systemd/user/org.gnome.Shell.target
/usr/lib/systemd/user/org.gnome.Shell@wayland.service
/usr/lib/systemd/user/org.gnome.Shell@x11.service
/usr/lib64/gnome-shell
/usr/lib64/gnome-shell/Gvc-1.0.typelib
/usr/lib64/gnome-shell/Shell-0.1.typelib
/usr/lib64/gnome-shell/St-1.0.typelib
/usr/lib64/gnome-shell/girepository-1.0
/usr/lib64/gnome-shell/girepository-1.0/Shew-0.typelib
/usr/lib64/gnome-shell/libgnome-shell-menu.so
/usr/lib64/gnome-shell/libgnome-shell.so
/usr/lib64/gnome-shell/libgvc.so
/usr/lib64/gnome-shell/libshew-0.so
/usr/lib64/gnome-shell/libst-1.0.so
/usr/libexec/gnome-shell-calendar-server
/usr/libexec/gnome-shell-hotplug-sniffer
/usr/libexec/gnome-shell-overrides-migration.sh
/usr/libexec/gnome-shell-perf-helper
/usr/libexec/gnome-shell-portal-helper
/usr/share/applications/evolution-calendar.desktop
/usr/share/applications/org.gnome.Shell.Extensions.desktop
/usr/share/applications/org.gnome.Shell.PortalHelper.desktop
/usr/share/applications/org.gnome.Shell.desktop
/usr/share/bash-completion/completions/gnome-extensions
/usr/share/dbus-1/interfaces/org.gnome.Shell.Extensions.xml
/usr/share/dbus-1/interfaces/org.gnome.Shell.Introspect.xml
/usr/share/dbus-1/interfaces/org.gnome.Shell.PadOsd.xml
/usr/share/dbus-1/interfaces/org.gnome.Shell.Screencast.xml
/usr/share/dbus-1/interfaces/org.gnome.Shell.Screenshot.xml
/usr/share/dbus-1/interfaces/org.gnome.ShellSearchProvider.xml
/usr/share/dbus-1/interfaces/org.gnome.ShellSearchProvider2.xml
/usr/share/dbus-1/services/org.gnome.ScreenSaver.service
/usr/share/dbus-1/services/org.gnome.Shell.CalendarServer.service
/usr/share/dbus-1/services/org.gnome.Shell.Extensions.service
/usr/share/dbus-1/services/org.gnome.Shell.HotplugSniffer.service
/usr/share/dbus-1/services/org.gnome.Shell.Notifications.service
/usr/share/dbus-1/services/org.gnome.Shell.PortalHelper.service
/usr/share/dbus-1/services/org.gnome.Shell.Screencast.service
/usr/share/doc/gnome-shell
/usr/share/doc/gnome-shell/README.md
/usr/share/glib-2.0/schemas/00_org.gnome.shell.gschema.override
/usr/share/glib-2.0/schemas/org.gnome.shell.gschema.xml
/usr/share/gnome-control-center/keybindings/50-gnome-shell-launchers.xml
/usr/share/gnome-control-center/keybindings/50-gnome-shell-screenshots.xml
/usr/share/gnome-control-center/keybindings/50-gnome-shell-system.xml
/usr/share/gnome-shell
/usr/share/gnome-shell/Gvc-1.0.gir
/usr/share/gnome-shell/Shell-0.1.gir
/usr/share/gnome-shell/St-1.0.gir
/usr/share/gnome-shell/extensions
/usr/share/gnome-shell/gir-1.0
/usr/share/gnome-shell/gir-1.0/Shew-0.gir
/usr/share/gnome-shell/gnome-shell-dbus-interfaces.gresource
/usr/share/gnome-shell/gnome-shell-icons.gresource
/usr/share/gnome-shell/gnome-shell-osk-layouts.gresource
/usr/share/gnome-shell/gnome-shell-theme.gresource
/usr/share/gnome-shell/org.gnome.ScreenSaver
/usr/share/gnome-shell/org.gnome.ScreenSaver.src.gresource
/usr/share/gnome-shell/org.gnome.Shell.Extensions
/usr/share/gnome-shell/org.gnome.Shell.Extensions.src.gresource
/usr/share/gnome-shell/org.gnome.Shell.Notifications
/usr/share/gnome-shell/org.gnome.Shell.Notifications.src.gresource
/usr/share/gnome-shell/org.gnome.Shell.Screencast
/usr/share/gnome-shell/org.gnome.Shell.Screencast.src.gresource
/usr/share/gnome-shell/perf-background.xml
/usr/share/gnome-shell/search-providers
/usr/share/icons/hicolor/scalable/apps/org.gnome.Shell.Extensions.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Shell.Extensions-symbolic.svg
/usr/share/licenses/gnome-shell
/usr/share/licenses/gnome-shell/COPYING
/usr/share/locale/af/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/an/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ar/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/as/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ast/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/be/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/bg/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/bn/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/bn_IN/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/bs/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ca/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ca@valencia/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ckb/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/cs/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/da/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/de/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/el/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/en_GB/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/eo/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/es/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/et/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/eu/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/fa/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/fi/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/fr/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/fur/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/fy/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ga/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/gd/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/gl/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/gu/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/he/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/hi/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/hr/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/hu/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ia/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/id/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/is/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/it/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ja/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/kab/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/kk/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/km/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/kn/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ko/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ku/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ky/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/lt/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/lv/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/mjw/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/mk/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ml/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/mr/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ms/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/nb/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ne/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/nl/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/nn/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/oc/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/or/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/os/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/pa/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/pl/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/pt/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/pt_BR/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ro/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ru/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/si/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/sk/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/sl/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/sr/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/sr@latin/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/sv/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ta/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/te/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/tg/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/th/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/tr/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/ug/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/uk/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/uz@cyrillic/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/vi/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/zh_CN/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/zh_HK/LC_MESSAGES/gnome-shell.mo
/usr/share/locale/zh_TW/LC_MESSAGES/gnome-shell.mo
/usr/share/man/man1/gnome-extensions.1.gz
/usr/share/man/man1/gnome-shell.1.gz
/usr/share/xdg-desktop-portal/portals
/usr/share/xdg-desktop-portal/portals/gnome-shell.portal
```

My Fedora 36 installation is quite pristine, I've done much crazy with it. I just installed it last night in fact. Should I open a new issue? :thinking:

**Comment by realmazharhussain** [comment] 2022-05-15 04:09
There have been a lot of bug reports with the same (or similar) issue. But they all went nowhere.

Thank you for such explainatory report. This will definitely help.

**Comment by realmazharhussain** [comment] 2022-05-15 04:50
> Should I open a new issue?

No, there are a lot of similar issues. If you want to talk in an issue created exactly for your problem, you can visit #29.

**Comment by realmazharhussain** [comment] 2022-05-15 04:57
> what other files might gdm-settings update on non-ubuntu systems?
> 
> I did some updates like background, welcome message, and showing weekend+seconds in top bar and I completely broke GDM.

The application is supposed to not touch any other file and from #29, it seems like that is the case.

Maybe the owner or file permissions of `/usr/share/gnome-shell/gnome-shell-theme.gresource` actually are the reason of the issue.

**Comment by fariszr** [comment] 2022-05-15 13:32
>  I completely broke GDM. on fedora 36

This is what happened to me too, I'm using an AMD GPU, so it has nothing to do with the drivers.
Unfortunately I couldn't wait for Mazhar to reply, so I reinstalled the distro after not finding any effective solution online.

**Comment by ProjectAzar** [comment] 2022-05-15 19:26
I'm not sure this will help with this issue, but as a related matter, I also broke GDM by attempting to assign a PNG, rather than SVG, as the background image. Upon application, Login Manager Settings hung and nearly crashed. When I logged out to test the change I was greeted with a "Something Broke" message and no ability to login. I switched to TTY and, after reviewing the app's code, guessed that I should be able to replace gnome-shell-theme.gresource with gnome-shell-theme.gresource.default, which solved my problem. 

System info below: 

OS: Fedora Linux 36 (Workstation Edition)
Kernel: 5.17.6-300.fc36.x86_64 
Uptime: 33 mins 
Packages: 1862 (rpm), 9 (flatpak) 
Shell: bash 5.1.16 
Resolution: 2560x1440 
DE: GNOME 42.0 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: guake 
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
Memory: 2415MiB / 32072MiB

**Comment by stefanmaric** [comment] 2022-05-16 13:49
> you can visit #29

Ha! Only if I had seen that issue before. :sweat_smile:

I will subscribe to that issue.

**Comment by realmazharhussain** [comment] 2022-05-21 11:14
I have changed some things in the app.

Here are new packages;
- [AppImage](https://github.com/realmazharhussain/gdm-settings/files/8747457/gdm-settings.AppImage.zip)
- [Flatpak](https://github.com/realmazharhussain/gdm-settings/files/8747458/gdm-settings.flatpak.zip)

You can install any of the above packages or install the app from source and check if it still breaks GDM.

**Comment by stefanmaric** [comment] 2022-05-23 10:59
@realmazharhussain gonna follow up on #29

**Comment by realmazharhussain** [comment] 2022-05-25 11:14
@ProjectAzar 

> I also broke GDM by attempting to assign a PNG, rather than SVG, as the background image.

I think that happened due to your system not supporting PNGs? I have never seen anyone else with this problem. I myself have used PNGs, JPEGs, etc. as background images and never had such problem.

Check if `libpng` is installed on your system and you can open PNG files using a GTK based image viewer like EOG, gThumb, etc.

**Comment by realmazharhussain** [comment] 2022-05-25 11:31
Since this issue is a duplicate of #29, I am closing it and I would suggest the OP @fariszr to move to #29 like @stefanmaric did.

I think I have found the solution for this issue though. Please see [this comment](https://github.com/realmazharhussain/gdm-settings/issues/29#issuecomment-1136772111) in #29 if you are interested in using this app without breaking your system.

**Closed by realmazharhussain** 2022-05-25 11:31 UTC
Labels: bug, duplicate
